### ISSUE TITLE
Coingecko throttling

### ISSUE THREAD

**Issue by fireduck64** [eth2353/eth2-staking-rewards-calculator#3]
This was with 18 validators and running a report from 2021-01-01 to 2021-12-31

Note, that 1607 from CoinGecko, that seems like it is asking for each day for each validator, which seems like a waste if that is what is actually happening.

`Fetching price data from CoinGecko:  66%|████████████████████████████▍              | 1065/1607 [01:06<00:33, 16.09it/s]
Traceback (most recent call last):
  File "/eth2-staking-rewards-calculator.git/main.py", line 426, in write_rewards_to_file
    _ = eth_price[dp.datetime.strftime(format="%d-%m-%Y")]
KeyError: '12-03-2021'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/eth2-staking-rewards-calculator.git/main.py", line 511, in <module>
    main()
  File "/eth2-staking-rewards-calculator.git/main.py", line 507, in main
    write_rewards_to_file(datapoints=datapoints)
  File "/eth2-staking-rewards-calculator.git/main.py", line 443, in write_rewards_to_file
    raise e
  File "/eth2-staking-rewards-calculator.git/main.py", line 436, in write_rewards_to_file
    raise Exception(f"Non-200 status code received from CoinGecko - "
Exception: Non-200 status code received from CoinGecko - <!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>
<title>Access denied | api.coingecko.com used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
`

**Comment by eth2353** [comment]
Thanks for the report!

Took a quick look at it, the CoinGecko API rate limiting was not handled correctly (rate limiting was only working for http but not for https), so it would fail at the first bad status code.

Fixed in the latest version ( 29950a6 ) - it now retries up to 5 times in case a bad status code is returned, while also respecting CoinGecko's retry-after header, if present.

As to your note, the price is only fetched once for each day 🙂

**Comment by eth2353** [comment]
By the way, if I may ask, is there any reason you're not using ETH2.tax ?

I am planning to add the following to the ETH2.tax website, at which point I think it will be the easier option:
- download CSV rewards for all validators at once (instead of having to click on the button for every validator)
- (opt-in) store the previous inputs in the browser cookies, so that you don't have to enter them every time you access the site

**Comment by fireduck64** [comment]
I like have a CLI plus I want to do some post processing.  Specifically, I'll be adding all my validators into one table and then possibly aggregating that table by week or month to be easier to handle by my accountant.

Also, I like having things I've downloaded and can just run.  Otherwise, part of my tax prep processes is figure out how the tooling has changed so I can adapt my programs to it.  This is what I have to do with coinbase and other exchanges.
